version: "3.9"

services:

  web-app:
    build:
      context: .
      dockerfile: ./2010/Dockerfile
      args:
        - PHP_VERSION=8.0
        - APP_PATH=app
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
    - ./app/src/:/app
  web-api:
      build:
        context: .
        dockerfile: ./2010/Dockerfile
        args:
          - PHP_VERSION=8.0
          - APP_PATH=api
      ports:
        - "8080:80"
      depends_on:
        - mysql
      volumes:
        - ./api/src/:/app
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - '8081:80'
      restart: always
      environment:
          PMA_HOST: mysql
      depends_on:
          - mysql
  mysql:
      image: mysql:5.7.38
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: nd_dev
        MYSQL_USER: admin
        MYSQL_PASSWORD: password
      ports:
        - "3306:3306"
      volumes:
        - ./mysql:/var/lib/mysql
volumes:
  app:
  api: